### ISSUE TITLE
Problem saving Transmitted models as new central files

### ISSUE THREAD

**Issue by walid-el** [bvn-architecture/RevitBatchProcessor#11] opened 2018-06-27 10:36 UTC
Hello, am trying to automate some of the task, and i get this error when i run my script, 
[error.txt](https://github.com/bvn-architecture/RevitBatchProcessor/files/2140824/error.txt)
please help ! how can i optimise my script to run on RevitBatchProcessor, it works fine when run inside Dynamo

**Comment by DanRumery** [comment] 2018-06-28 01:15
Hi Walid,

I see you found the cause of your problem (Issue #9 - If there are two versions of Dynamo installed for the same Revit version, RBP fails to run Dynamo task script.) Let me know if you still have any issues after the workaround.

**Comment by walid-el** [comment] 2018-07-03 11:54
Hello Dan, i removed the old version of dynamo, now i only have dynamo core and dynamo Revit, but still can't run my script, the script, here is the error report , thank you 
[error.txt](https://github.com/bvn-architecture/RevitBatchProcessor/files/2159121/error.txt)

**Comment by DanRumery** [comment] 2018-07-03 15:00
@walid-el 

Hi Walid,

The error is related to attempting to create a new local file from what seems to be a transmitted model. From what I gather you'll have to save those files as new Central files first. (I don't have much experience with transmitted files so I'm not sure).

[See: Open a Transmitted Model](https://knowledge.autodesk.com/support/revit-products/learn-explore/caas/CloudHelp/cloudhelp/2018/ENU/Revit-AddIns/files/GUID-127C82C6-84A3-4DBE-B6B9-A90308ED495F-htm.html)

Alternatively, you could also try the 'detach from Central' option in the Revit Batch Processor GUI and see if that works.

Let me know if the above suggestions help or not.

**Comment by walid-el** [comment] 2018-07-05 17:04
hello, i have tried the open with detached, it worked but it prompt me to save as detached, (which make it redundant) and the it s not saved as detached but as new central named detached. 
my goal is to open a number of central files that have been moved and run my script which will save the file as a central in a new location. 
help ! please

**Comment by DanRumery** [comment] 2018-07-05 18:12
@walid-el 

Are you able to send me a copy of one of the transmitted Revit models you're trying to process? It would be useful for me to find a fix for this. Ideally you can remove all the content in the file, as long as its still a 'transmitted' file.

I could add an option in RBP to allow opening Central files **directly**, but I am worried that this option is dangerous for most users. I would prefer if there was another workaround.

You say it prompts you to detach, when does it do this? While RBP is still running? Or after when you open the file yourself?

Maybe if you also show me the script that saves the file I can help you troubleshoot that.

**Comment by DanRumery** [comment] 2018-07-06 11:46
@walid-el 

I think I've found the cause of the problem! **The python script below should work for transmitted files.** You will still need to use the **detach from central** option in RBP:

```python
import clr
import System
clr.AddReference("System.Core")
clr.ImportExtensions(System.Linq)

clr.AddReference("RevitAPI")
clr.AddReference("RevitAPIUI")
from Autodesk.Revit.DB import *

import revit_script_util
from revit_script_util import Output

from System.IO import Path
import revit_dynamo_util
import revit_file_util


# This should point to your Dynamo task script (*.dyn) file.
DYNAMO_SCRIPT_FILE_PATH = r"C:\BatchProcessing\MyDynamoTaskScript.dyn"

# Location to save the processed Revit files to.
SAVE_FOLDER_PATH = r"C:\BatchProcessing\SavedRevitFiles"


def SaveAsNewCentral(doc, modelPath, overwrite=True, clearTransmitted=False):
  saveAsOptions = SaveAsOptions()
  saveAsOptions.Compact = True
  saveAsOptions.OverwriteExistingFile = overwrite
  saveAsOptions.MaximumBackups = 1
  worksharingSaveAsOptions = WorksharingSaveAsOptions()
  worksharingSaveAsOptions.SaveAsCentral = True
  worksharingSaveAsOptions.ClearTransmitted = clearTransmitted
  saveAsOptions.SetWorksharingOptions(worksharingSaveAsOptions)
  doc.SaveAs(modelPath, saveAsOptions)
  return

def SaveRevitFile(doc, originalRevitFilePath, saveFolderPath):
  # Save the Revit model / family file in the new location.
  revitFileName = Path.GetFileName(originalRevitFilePath)
  saveRevitFilePath = Path.Combine(saveFolderPath, revitFileName)
  if doc.IsWorkshared: # For workshared models.
    saveRevitModelPath = ModelPathUtils.ConvertUserVisiblePathToModelPath(saveRevitFilePath)
    SaveAsNewCentral(
        doc,
        saveRevitModelPath,
        True, # NOTE: this means overwrite the existing file if it exists; set to False if this is not desired.
        True  # NOTE: this means clear the transmitted flag.
              # (This only works on transmitted files. It will cause an error for non-transmitted files!)
      )
    revit_file_util.RelinquishAll(doc) # Need to relinquish ownership of worksets after saving as new Central file.
  else: # For non-workshared models and family files.
    revit_file_util.SaveAs(
        doc,
        saveRevitFilePath,
        True # NOTE: this means overwrite the existing file if it exists; set to False if this is not desired.
      )
  return


sessionId = revit_script_util.GetSessionId()
uiapp = revit_script_util.GetUIApplication()

# NOTE: these only make sense for batch Revit file processing mode.
doc = revit_script_util.GetScriptDocument()
revitFilePath = revit_script_util.GetRevitFilePath()
projectFolderName = revit_script_util.GetProjectFolderName()

Output()
Output("This task script is running!")

# Execute the Dynamo script
revit_dynamo_util.ExecuteDynamoScript(uiapp, DYNAMO_SCRIPT_FILE_PATH)

# Save the Revit file to the destination folder.
SaveRevitFile(doc, revitFilePath, SAVE_FOLDER_PATH)
```

You will notice that this is very similar to the sample python script that saves a new central file. The only difference is that I've defined a new SaveAsNewCentral() function in this script that takes a parameter 'clearTransmitted'. When this parameter is set to True, it will remove the transmitted state from the new central file.

Hope this script works for you!

**Comment by DanRumery** [comment] 2018-07-08 13:52
In RBP v1.2.8 the helper function `revit_file_util.SaveAsNewCentral()` now takes an optional parameter `clearTransmitted` that should be set to `True` if processing transmitted model files, `False` if processing normal model files.

NOTE: unfortunately I haven't found a way to detect which files are transmitted and which aren't so for the moment, the user has to know which type of model file they're dealing with and set the parameter appropriately.

**Comment by walid-el** [comment] 2018-07-10 09:36
hello Dan 
sorry for my late reply, i will try the new version and give you my feed back, do you still need the transmited file and script !?

**Comment by DanRumery** [comment] 2018-07-11 02:02
@walid-el 

Ok can you also please send me the custom node `Document.SaveAs`  that you're using in your dynamo script? I need to see how that node is performing the save as new Central.

Note that, no matter which method you use to save the file, it will have to be 'detach from Central' first, *not* 'Create New Local'.

**Comment by DanRumery** [comment] 2018-07-11 02:11
@walid-el 

Hi Walid,

I've just installed the **Clockwork package 1.31.2** so now I have the `Document.SaveAs` node.

I tested your Dynamo script and with the RBP option '**Detach from Central**' it correctly saves a new Central model with the transmitted flag cleared! :)

Please make sure you're setting 'Detach from Central' in the UI!

**Comment by walid-el** [comment] 2018-07-11 09:06
thank you Dan,
will do some work today and let you know how it s went

**Comment by walid-el** [comment] 2018-07-12 16:15
Hello Dan, yes the option with detached worked, thank you so much for your help, 
i wanted ask if there is any way to open detached and discard worksets.

DetachAndDiscardWorksets | Detach the model being opened from its central model and discard worksets/worksharing.

thank you

**Comment by DanRumery** [comment] 2018-07-13 00:16
@walid-el 

Great it worked!

At the moment there isn't an option in RBP. I'll add it as an Issue / enhancement.

**Comment by DanRumery** [comment] 2018-07-13 00:17
Solution:

Use '**Detach from Central**' option in RBP, use `Document.SaveAs` node from **Clockwork package 1.31.2**

**Closed by DanRumery** 2018-07-13 00:17 UTC
Labels: bug

**Comment by RickBIM** [comment] 2023-07-26 15:35
> Hello Dan, i removed the old version of dynamo, now i only have dynamo core and dynamo Revit, but still can't run my script, the script, here is the error report , thank you [error.txt](https://github.com/bvn-architecture/RevitBatchProcessor/files/2159121/error.txt)

Hello, how do you removed the old version of Dynamo? I have the same issue here
