### ISSUE TITLE
Can't import revit_script_util and revit_file_util

### ISSUE THREAD

**Issue by nhanhuynhdanh** [bvn-architecture/RevitBatchProcessor#95] opened 2022-09-25 16:41 UTC
Sorry, can you help me setting json file, i can't add this reference 
Thanks

![ref](https://user-images.githubusercontent.com/86488950/192154989-ad961630-1de2-4c0a-a3b1-989f0c20ca22.png)

**Comment by punderscoresmithuk** [comment] 2022-09-26 00:58
Hi @nhanhuynhdanh,

What's your error message? Why are you importing the Output function and then overwriting it? You're going to need an indentation on your if, else aswell.

Cheers

**Comment by nhanhuynhdanh** [comment] 2022-09-26 13:13
thanks @punderscoresmithuk , i'm newbie,
please take a look in the json file setting
the import are missing, can you advise me fixing it?
![image](https://user-images.githubusercontent.com/86488950/192285834-f67ec9b4-2f4c-4570-b758-0a9e4d5d6ff5.png)

**Comment by punderscoresmithuk** [comment] 2022-09-26 21:01
Hi @nhanhuynhdanh 

You are altering your visual studio code python settings by modifying that json. You can google the error messages you are getting and receive results which explain it, such as [here](https://stackoverflow.com/questions/68486207/import-could-not-be-resolved-could-not-be-resolved-from-source-pylance-in-vs-cod), [here](https://stackoverflow.com/questions/65252074/import-path-to-own-script-could-not-be-resolved-pylance-reportmissingimports) or [here](https://stackoverflow.com/questions/72322120/vscode-import-x-could-not-be-resolved-even-though-listed-under-helpmodules)

It's probably worth checking the Revit API or Dynamo forums for more general Revit API questions. This is not a bug with Revit Batch Processor so I'm going to close this issue. 

Cheers, Pete

**Closed by punderscoresmithuk** 2022-09-26 21:01 UTC
